name: Nightly builds
env:
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
on:
    workflow_dispatch:
    schedule:
        - cron: '0 0 * * *'

jobs:
    nightly_build_on_linux:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '16.x'
            - name: update package directory
              run: sudo apt update
            - name: install rpm and libarchive
              run: sudo apt install rpm libarchive-tools
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:linux
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: uploading rpm artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-rpm
                  path: release/Neuron-*.rpm
            - name: upload deb artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-deb
                  path: release/Neuron-*.deb
            - name: upload appimage artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-appimage
                  path: release/Neuron-*.AppImage
            - name: upload snap artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-snap
                  path: release/Neuron-*.snap
            - name: upload pacman artifact
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-pacman
                  path: release/Neuron-*.pacman

    nightly_build_on_mac:
        runs-on: macos-11
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '16.x'
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:mac
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-macos
                  path: release/Neuron-*.dmg

    nightly_build_on_win:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@master
              with:
                  node-version: '16.x'
            - name: install dependencies
              run: npm install
            - name: run unit tests
              run: npm run test
            - name: build
              run: npm run electron:windows
            - name: fetch current version
              id: ver_name
              uses: notiz-dev/github-action-json-property@release
              with:
                  path: 'package.json'
                  prop_path: 'version'
            - name: upload build artifacts
              uses: actions/upload-artifact@v2
              with:
                  name: Neuron-nightly-win
                  path: release\Neuron-*.exe
